USE ROLE ACCOUNTADMIN;
USE WAREHOUSE NORTHSTAR_WH;
USE DATABASE NORTHSTAR_DB;
USE SCHEMA RAW;

-- CSV ingestion format
CREATE FILE FORMAT IF NOT EXISTS CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('NULL', 'null', '');

-- Semi-structured JSON format
CREATE FILE FORMAT IF NOT EXISTS JSON_FORMAT
    TYPE = JSON;

-- Internal landing stage
CREATE STAGE IF NOT EXISTS NORTHSTAR_STAGE
    COMMENT = 'Internal landing stage for NorthStar Commerce raw data';