USE ROLE ACCOUNTADMIN;
USE WAREHOUSE NORTHSTAR_WH;
USE DATABASE NORTHSTAR_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW_CUSTOMERS (
    CUSTOMER_ID       NUMBER,
    FIRST_NAME        VARCHAR,
    LAST_NAME         VARCHAR,
    EMAIL             VARCHAR,
    COUNTRY           VARCHAR,
    SIGNUP_DATE       DATE,
    CUSTOMER_STATUS   VARCHAR,
    SOURCE_FILE       VARCHAR,
    INGESTED_AT       TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAW_PRODUCTS (
    PRODUCT_ID        NUMBER,
    PRODUCT_NAME      VARCHAR,
    CATEGORY          VARCHAR,
    UNIT_PRICE        NUMBER(10,2),
    IS_ACTIVE         BOOLEAN,
    SOURCE_FILE       VARCHAR,
    INGESTED_AT       TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAW_ORDERS (
    ORDER_ID          NUMBER,
    CUSTOMER_ID       NUMBER,
    PRODUCT_ID        NUMBER,
    ORDER_DATE        DATE,
    QUANTITY          NUMBER,
    UNIT_PRICE        NUMBER(10,2),
    ORDER_STATUS      VARCHAR,
    SOURCE_FILE       VARCHAR,
    INGESTED_AT       TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAW_WEB_EVENTS (
    EVENT_DATA        VARIANT,
    SOURCE_FILE       VARCHAR,
    INGESTED_AT       TIMESTAMP_NTZ
);