-- ============================================================
-- NorthStar Commerce
-- Snowflake Environment Setup
-- ============================================================

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS NORTHSTAR_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Development warehouse for NorthStar Commerce';

CREATE DATABASE IF NOT EXISTS NORTHSTAR_DB;

CREATE SCHEMA IF NOT EXISTS NORTHSTAR_DB.RAW;
CREATE SCHEMA IF NOT EXISTS NORTHSTAR_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS NORTHSTAR_DB.CONTROL;
CREATE SCHEMA IF NOT EXISTS NORTHSTAR_DB.DBT_DEV;
CREATE SCHEMA IF NOT EXISTS NORTHSTAR_DB.DBT_TRANSFORM;
CREATE SCHEMA IF NOT EXISTS NORTHSTAR_DB.GOLD;

USE WAREHOUSE NORTHSTAR_WH;
USE DATABASE NORTHSTAR_DB;